### PR TITLE
feat: mps vehiclepersist

### PR DESCRIPTION
**Pull request by Maximus7474**
Added a resource that simply saves the vehicles left outside at server shutdown and respawns them after the server starts again.

### CODE REVIEW

**Review by LukeWasTakenn — CHANGES_REQUESTED** [review]
Can you add a dash or an underscore to the resource name to match others?

**Comment by Maximus7474** [comment]
You mean for the impound ? It's the only on missing one ?
image

**Comment by LukeWasTakenn** [comment]
Your PR doesn't include it for vehiclepersist, #16 adds it to the impound.

**Comment by Maximus7474** [comment]
Sorry about that luke, was retarded

**Review by LukeWasTakenn — APPROVED** [review]

**Pull request merged**
